language: objective-c
osx_image: xcode7
xcode_project: continuous.xcodeproj
xcode_scheme: continuous
xcode_sdk: iphonesimulator9.0
#  - python -c 'print "Hello"'

script:
  - fastlane ios smoketest
  - ls -l fastlane/screenshots/
  - python -c 'print "DONE"'