# I'm on master
language: objective-c
osx_image: xcode7
xcode_project: continuous.xcodeproj
xcode_scheme: continuous
xcode_sdk: iphonesimulator9.0

script:
- fastlane ios compile

branches:
  only:
  - master
